repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0
#     hooks:
#     -   id: trailing-whitespace      # Removes trailing whitespace at the end of lines
#     -   id: end-of-file-fixer        # Adds an empty line at the end of file

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff        # python linter
    -   id: ruff-format # code formatter

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy  # static type checking
